name: SFTP Connection Check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Print config (masked)
        run: |
          echo "Host set: ${{ secrets.SFTP_HOST != '' }}"
          echo "User set: ${{ secrets.SFTP_USERNAME != '' }}"
          echo "Port set: ${{ secrets.SFTP_PORT != '' }}"
          echo "Remote path set: ${{ secrets.REMOTE_PLUGIN_PATH != '' }}"

      - name: SSH to server and list plugin directory
        uses: appleboy/ssh-action@v1.0.3
        env:
          REMOTE_PLUGIN_PATH: ${{ secrets.REMOTE_PLUGIN_PATH }}
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          script: |
            set -e
            echo "Listing $REMOTE_PLUGIN_PATH"
            ls -la "$REMOTE_PLUGIN_PATH"
            echo "OK: remote path accessible"
