name: SFTP Connection Check

on:
  workflow_dispatch:

jobs:
  sftp-list:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass (for non-interactive sftp)
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: List remote plugin directory via SFTP
        env:
          HOST: ${{ secrets.SFTP_HOST }}
          PORT: ${{ secrets.SFTP_PORT }}
          USER: ${{ secrets.SFTP_USERNAME }}
          PASS: ${{ secrets.SFTP_PASSWORD }}
          REMOTE: ${{ secrets.REMOTE_PLUGIN_PATH }}
        run: |
          echo "Listing $REMOTE on $USER@$HOST:$PORT"
          sshpass -p "$PASS" sftp -oBatchMode=no -oStrictHostKeyChecking=no -P "$PORT" "$USER@$HOST" <<EOF
ls -la $REMOTE
EOF
          echo "OK: remote path accessible"